-- LEVEL 5 — SINGLE-ROW FUNCTIONS

-- Practice these functions:

-- Character

-- UPPER()
-- LOWER()
-- INITCAP()
-- LENGTH()
-- SUBSTR()

-- Number

-- ROUND()
-- TRUNC()
-- MOD()

-- Date

-- SYSDATE
-- MONTHS_BETWEEN()
-- ADD_MONTHS()
-- NEXT_DAY()
-- LAST_DAY()
-- Questions
-- Display employee names in uppercase.
-- Display employee names in lowercase.
-- Display employee names and their name length.
-- Display the first 3 characters of every employee name.
-- Display the last 2 characters of every employee name.
-- Display employee name and salary rounded to the nearest 100.
-- Display employee name and the number of months they have worked in the company.
-- Display employee name and their hire date along with the date after adding 6 months.